<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>Rewrite "rethrow" with async/await</title>
</head>
<body>

    <script>

        /*
        class HttpError extends Error{
            constructor(response) {
                super(`${response.status} for ${response.url}`);
                this.name = 'HttpError';
                this.response = response;
            }
        }

        function loadJson(url) {
            return fetch(url).then(response => {
                if(response.status == 200) {
                    return response.json();
                }else{
                    throw new Error(response.status);
                }
            });
        }

        //Peça um nome de usuário até que o github retorne um usuário válido
        function demoGitHubUser() {
            let name = prompt("Enter a name?", "iliakan");

            return loadJson(`https://api.github.com/users/${name}`).then(user => {
                console.log(`Full name: ${user.name}.`);
                return user;
            }).catch(err => {
                if(err instanceof HttpError && err.response.status == 404) {
                    console.log("No such user, please reenter.");
                    return demoGitHubUser();
                }else{
                    throw err;
                }
            });
        }

        demoGitHubUser();
        */

        //Reescreva-o usando async/await em vez de .then/catch.
        
        class HttpError extends Error{
            constructor(response) {
                super(`${response.status} for ${response.url}`);
                this.name = 'HttpError';
                this.response = response;
            }
        }

        
        async function loadJson(url) {
            let response = await fetch(url);
            if(response.status === 200) {
                let json = await response.json();
                return json;
            }else{
                throw new HttpError(response);
            }
        }

        //Peça um nome de usuário até que o github retorne um usuário válido
        async function demoGitHubUser() {
            let flag = true;
            while(flag) {
                let name = prompt("Enter a name?", "iliakan");
                try {
                    let result = await loadJson(`https://api.github.com/users/${name}`);
                    console.log(`Full name: ${result.name}.`);
                    flag = false;
                    return result; //object
                } catch (error) {
                    if(error instanceof HttpError && error.response.status == 404) {
                        console.log("No such user, please reenter.");
                        flag = true;
                    }else{
                        flag = true;
                        throw error;
                    }
                }
            }
            
        }
        
        
        console.log(demoGitHubUser());
        //console.log()
    </script>

</body>
</html>